// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"gas-detect/internal/data/model/ent/migrate"

	"gas-detect/internal/data/model/ent/gasdetect"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// GasDetect is the client for interacting with the GasDetect builders.
	GasDetect *GasDetectClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.GasDetect = NewGasDetectClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		GasDetect: NewGasDetectClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		GasDetect: NewGasDetectClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		GasDetect.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.GasDetect.Use(hooks...)
}

// GasDetectClient is a client for the GasDetect schema.
type GasDetectClient struct {
	config
}

// NewGasDetectClient returns a client for the GasDetect from the given config.
func NewGasDetectClient(c config) *GasDetectClient {
	return &GasDetectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gasdetect.Hooks(f(g(h())))`.
func (c *GasDetectClient) Use(hooks ...Hook) {
	c.hooks.GasDetect = append(c.hooks.GasDetect, hooks...)
}

// Create returns a builder for creating a GasDetect entity.
func (c *GasDetectClient) Create() *GasDetectCreate {
	mutation := newGasDetectMutation(c.config, OpCreate)
	return &GasDetectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GasDetect entities.
func (c *GasDetectClient) CreateBulk(builders ...*GasDetectCreate) *GasDetectCreateBulk {
	return &GasDetectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GasDetect.
func (c *GasDetectClient) Update() *GasDetectUpdate {
	mutation := newGasDetectMutation(c.config, OpUpdate)
	return &GasDetectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GasDetectClient) UpdateOne(gd *GasDetect) *GasDetectUpdateOne {
	mutation := newGasDetectMutation(c.config, OpUpdateOne, withGasDetect(gd))
	return &GasDetectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GasDetectClient) UpdateOneID(id int32) *GasDetectUpdateOne {
	mutation := newGasDetectMutation(c.config, OpUpdateOne, withGasDetectID(id))
	return &GasDetectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GasDetect.
func (c *GasDetectClient) Delete() *GasDetectDelete {
	mutation := newGasDetectMutation(c.config, OpDelete)
	return &GasDetectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GasDetectClient) DeleteOne(gd *GasDetect) *GasDetectDeleteOne {
	return c.DeleteOneID(gd.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *GasDetectClient) DeleteOneID(id int32) *GasDetectDeleteOne {
	builder := c.Delete().Where(gasdetect.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GasDetectDeleteOne{builder}
}

// Query returns a query builder for GasDetect.
func (c *GasDetectClient) Query() *GasDetectQuery {
	return &GasDetectQuery{
		config: c.config,
	}
}

// Get returns a GasDetect entity by its id.
func (c *GasDetectClient) Get(ctx context.Context, id int32) (*GasDetect, error) {
	return c.Query().Where(gasdetect.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GasDetectClient) GetX(ctx context.Context, id int32) *GasDetect {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GasDetectClient) Hooks() []Hook {
	return c.hooks.GasDetect
}
