// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gas-detect/internal/data/model/ent/gasdetect"
	"gas-detect/internal/data/model/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GasDetectDelete is the builder for deleting a GasDetect entity.
type GasDetectDelete struct {
	config
	hooks    []Hook
	mutation *GasDetectMutation
}

// Where appends a list predicates to the GasDetectDelete builder.
func (gdd *GasDetectDelete) Where(ps ...predicate.GasDetect) *GasDetectDelete {
	gdd.mutation.Where(ps...)
	return gdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gdd *GasDetectDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gdd.hooks) == 0 {
		affected, err = gdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GasDetectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gdd.mutation = mutation
			affected, err = gdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gdd.hooks) - 1; i >= 0; i-- {
			if gdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gdd *GasDetectDelete) ExecX(ctx context.Context) int {
	n, err := gdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gdd *GasDetectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: gasdetect.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: gasdetect.FieldID,
			},
		},
	}
	if ps := gdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GasDetectDeleteOne is the builder for deleting a single GasDetect entity.
type GasDetectDeleteOne struct {
	gdd *GasDetectDelete
}

// Exec executes the deletion query.
func (gddo *GasDetectDeleteOne) Exec(ctx context.Context) error {
	n, err := gddo.gdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gasdetect.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gddo *GasDetectDeleteOne) ExecX(ctx context.Context) {
	gddo.gdd.ExecX(ctx)
}
