// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gas-detect/internal/data/model/ent/gasdetect"
	"gas-detect/internal/data/model/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GasDetectQuery is the builder for querying GasDetect entities.
type GasDetectQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GasDetect
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GasDetectQuery builder.
func (gdq *GasDetectQuery) Where(ps ...predicate.GasDetect) *GasDetectQuery {
	gdq.predicates = append(gdq.predicates, ps...)
	return gdq
}

// Limit adds a limit step to the query.
func (gdq *GasDetectQuery) Limit(limit int) *GasDetectQuery {
	gdq.limit = &limit
	return gdq
}

// Offset adds an offset step to the query.
func (gdq *GasDetectQuery) Offset(offset int) *GasDetectQuery {
	gdq.offset = &offset
	return gdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gdq *GasDetectQuery) Unique(unique bool) *GasDetectQuery {
	gdq.unique = &unique
	return gdq
}

// Order adds an order step to the query.
func (gdq *GasDetectQuery) Order(o ...OrderFunc) *GasDetectQuery {
	gdq.order = append(gdq.order, o...)
	return gdq
}

// First returns the first GasDetect entity from the query.
// Returns a *NotFoundError when no GasDetect was found.
func (gdq *GasDetectQuery) First(ctx context.Context) (*GasDetect, error) {
	nodes, err := gdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gasdetect.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gdq *GasDetectQuery) FirstX(ctx context.Context) *GasDetect {
	node, err := gdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GasDetect ID from the query.
// Returns a *NotFoundError when no GasDetect ID was found.
func (gdq *GasDetectQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = gdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gasdetect.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gdq *GasDetectQuery) FirstIDX(ctx context.Context) int32 {
	id, err := gdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GasDetect entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GasDetect entity is found.
// Returns a *NotFoundError when no GasDetect entities are found.
func (gdq *GasDetectQuery) Only(ctx context.Context) (*GasDetect, error) {
	nodes, err := gdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gasdetect.Label}
	default:
		return nil, &NotSingularError{gasdetect.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gdq *GasDetectQuery) OnlyX(ctx context.Context) *GasDetect {
	node, err := gdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GasDetect ID in the query.
// Returns a *NotSingularError when more than one GasDetect ID is found.
// Returns a *NotFoundError when no entities are found.
func (gdq *GasDetectQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = gdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gasdetect.Label}
	default:
		err = &NotSingularError{gasdetect.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gdq *GasDetectQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := gdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GasDetects.
func (gdq *GasDetectQuery) All(ctx context.Context) ([]*GasDetect, error) {
	if err := gdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gdq *GasDetectQuery) AllX(ctx context.Context) []*GasDetect {
	nodes, err := gdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GasDetect IDs.
func (gdq *GasDetectQuery) IDs(ctx context.Context) ([]int32, error) {
	var ids []int32
	if err := gdq.Select(gasdetect.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gdq *GasDetectQuery) IDsX(ctx context.Context) []int32 {
	ids, err := gdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gdq *GasDetectQuery) Count(ctx context.Context) (int, error) {
	if err := gdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gdq *GasDetectQuery) CountX(ctx context.Context) int {
	count, err := gdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gdq *GasDetectQuery) Exist(ctx context.Context) (bool, error) {
	if err := gdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gdq *GasDetectQuery) ExistX(ctx context.Context) bool {
	exist, err := gdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GasDetectQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gdq *GasDetectQuery) Clone() *GasDetectQuery {
	if gdq == nil {
		return nil
	}
	return &GasDetectQuery{
		config:     gdq.config,
		limit:      gdq.limit,
		offset:     gdq.offset,
		order:      append([]OrderFunc{}, gdq.order...),
		predicates: append([]predicate.GasDetect{}, gdq.predicates...),
		// clone intermediate query.
		sql:    gdq.sql.Clone(),
		path:   gdq.path,
		unique: gdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedTime time.Time `json:"created_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GasDetect.Query().
//		GroupBy(gasdetect.FieldCreatedTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gdq *GasDetectQuery) GroupBy(field string, fields ...string) *GasDetectGroupBy {
	grbuild := &GasDetectGroupBy{config: gdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gdq.sqlQuery(ctx), nil
	}
	grbuild.label = gasdetect.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedTime time.Time `json:"created_time,omitempty"`
//	}
//
//	client.GasDetect.Query().
//		Select(gasdetect.FieldCreatedTime).
//		Scan(ctx, &v)
func (gdq *GasDetectQuery) Select(fields ...string) *GasDetectSelect {
	gdq.fields = append(gdq.fields, fields...)
	selbuild := &GasDetectSelect{GasDetectQuery: gdq}
	selbuild.label = gasdetect.Label
	selbuild.flds, selbuild.scan = &gdq.fields, selbuild.Scan
	return selbuild
}

func (gdq *GasDetectQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gdq.fields {
		if !gasdetect.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gdq.path != nil {
		prev, err := gdq.path(ctx)
		if err != nil {
			return err
		}
		gdq.sql = prev
	}
	return nil
}

func (gdq *GasDetectQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GasDetect, error) {
	var (
		nodes = []*GasDetect{}
		_spec = gdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*GasDetect).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &GasDetect{config: gdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gdq *GasDetectQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gdq.querySpec()
	_spec.Node.Columns = gdq.fields
	if len(gdq.fields) > 0 {
		_spec.Unique = gdq.unique != nil && *gdq.unique
	}
	return sqlgraph.CountNodes(ctx, gdq.driver, _spec)
}

func (gdq *GasDetectQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gdq *GasDetectQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gasdetect.Table,
			Columns: gasdetect.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: gasdetect.FieldID,
			},
		},
		From:   gdq.sql,
		Unique: true,
	}
	if unique := gdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gasdetect.FieldID)
		for i := range fields {
			if fields[i] != gasdetect.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gdq *GasDetectQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gdq.driver.Dialect())
	t1 := builder.Table(gasdetect.Table)
	columns := gdq.fields
	if len(columns) == 0 {
		columns = gasdetect.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gdq.sql != nil {
		selector = gdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gdq.unique != nil && *gdq.unique {
		selector.Distinct()
	}
	for _, p := range gdq.predicates {
		p(selector)
	}
	for _, p := range gdq.order {
		p(selector)
	}
	if offset := gdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GasDetectGroupBy is the group-by builder for GasDetect entities.
type GasDetectGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gdgb *GasDetectGroupBy) Aggregate(fns ...AggregateFunc) *GasDetectGroupBy {
	gdgb.fns = append(gdgb.fns, fns...)
	return gdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gdgb *GasDetectGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gdgb.path(ctx)
	if err != nil {
		return err
	}
	gdgb.sql = query
	return gdgb.sqlScan(ctx, v)
}

func (gdgb *GasDetectGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gdgb.fields {
		if !gasdetect.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gdgb *GasDetectGroupBy) sqlQuery() *sql.Selector {
	selector := gdgb.sql.Select()
	aggregation := make([]string, 0, len(gdgb.fns))
	for _, fn := range gdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gdgb.fields)+len(gdgb.fns))
		for _, f := range gdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gdgb.fields...)...)
}

// GasDetectSelect is the builder for selecting fields of GasDetect entities.
type GasDetectSelect struct {
	*GasDetectQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gds *GasDetectSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gds.prepareQuery(ctx); err != nil {
		return err
	}
	gds.sql = gds.GasDetectQuery.sqlQuery(ctx)
	return gds.sqlScan(ctx, v)
}

func (gds *GasDetectSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gds.sql.Query()
	if err := gds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
