// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gas-detect/internal/data/model/ent/gasdetect"
	"gas-detect/internal/data/model/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gasdetectMixin := schema.GasDetect{}.Mixin()
	gasdetectMixinFields0 := gasdetectMixin[0].Fields()
	_ = gasdetectMixinFields0
	gasdetectFields := schema.GasDetect{}.Fields()
	_ = gasdetectFields
	// gasdetectDescCreatedTime is the schema descriptor for created_time field.
	gasdetectDescCreatedTime := gasdetectMixinFields0[1].Descriptor()
	// gasdetect.DefaultCreatedTime holds the default value on creation for the created_time field.
	gasdetect.DefaultCreatedTime = gasdetectDescCreatedTime.Default.(func() time.Time)
	// gasdetectDescIsDeleted is the schema descriptor for is_deleted field.
	gasdetectDescIsDeleted := gasdetectMixinFields0[2].Descriptor()
	// gasdetect.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	gasdetect.DefaultIsDeleted = gasdetectDescIsDeleted.Default.(bool)
}
