// Code generated by ent, DO NOT EDIT.

package gasdetect

import (
	"time"
)

const (
	// Label holds the string label denoting the gasdetect type in the database.
	Label = "gas_detect"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedTime holds the string denoting the created_time field in the database.
	FieldCreatedTime = "created_time"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldMetrics holds the string denoting the metrics field in the database.
	FieldMetrics = "metrics"
	// Table holds the table name of the gasdetect in the database.
	Table = "gas_detects"
)

// Columns holds all SQL columns for gasdetect fields.
var Columns = []string{
	FieldID,
	FieldCreatedTime,
	FieldIsDeleted,
	FieldMetrics,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedTime holds the default value on creation for the "created_time" field.
	DefaultCreatedTime func() time.Time
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
)
