apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: gas-detect
  name: gas-detect
  namespace: gas-detect
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 31718
  selector:
    app: gas-detect
  sessionAffinity: None
  type: NodePort