// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gas-detect/internal/biz"
	"gas-detect/internal/conf"
	"gas-detect/internal/data"
	"gas-detect/internal/server"
	"gas-detect/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	gasDetectRepo := data.NewGasDetectRepo(dataData, logger)
	gasDetectUsecase := biz.NewGasDetectUsecase(gasDetectRepo, logger)
	gasDetectService := service.NewGasDetectService(gasDetectUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, gasDetectService)
	httpServer := server.NewHTTPServer(confServer, logger, gasDetectService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
