// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GasDetectsColumns holds the columns for the "gas_detects" table.
	GasDetectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true},
		{Name: "created_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "metrics", Type: field.TypeJSON, Nullable: true},
	}
	// GasDetectsTable holds the schema information for the "gas_detects" table.
	GasDetectsTable = &schema.Table{
		Name:       "gas_detects",
		Columns:    GasDetectsColumns,
		PrimaryKey: []*schema.Column{GasDetectsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GasDetectsTable,
	}
)

func init() {
}
