// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: api/gas/gas_detect.proto

package gen

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGasDetectBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *CreateGasDetectBody) Reset() {
	*x = CreateGasDetectBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGasDetectBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGasDetectBody) ProtoMessage() {}

func (x *CreateGasDetectBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGasDetectBody.ProtoReflect.Descriptor instead.
func (*CreateGasDetectBody) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGasDetectBody) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName       string `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	Concentration  string `protobuf:"bytes,2,opt,name=concentration,proto3" json:"concentration,omitempty"`
	AnalysisResult string `protobuf:"bytes,3,opt,name=analysisResult,proto3" json:"analysisResult,omitempty"`
}

func (x *Metric) Reset() {
	*x = Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Metric) GetConcentration() string {
	if x != nil {
		return x.Concentration
	}
	return ""
}

func (x *Metric) GetAnalysisResult() string {
	if x != nil {
		return x.AnalysisResult
	}
	return ""
}

type CreateGasDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *CreateGasDetectBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CreateGasDetectRequest) Reset() {
	*x = CreateGasDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGasDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGasDetectRequest) ProtoMessage() {}

func (x *CreateGasDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGasDetectRequest.ProtoReflect.Descriptor instead.
func (*CreateGasDetectRequest) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGasDetectRequest) GetBody() *CreateGasDetectBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ListGasDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize int32  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNo   int32  `protobuf:"varint,4,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	Sorter   string `protobuf:"bytes,5,opt,name=sorter,proto3" json:"sorter,omitempty"`
}

func (x *ListGasDetectRequest) Reset() {
	*x = ListGasDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGasDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGasDetectRequest) ProtoMessage() {}

func (x *ListGasDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGasDetectRequest.ProtoReflect.Descriptor instead.
func (*ListGasDetectRequest) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{3}
}

func (x *ListGasDetectRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGasDetectRequest) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListGasDetectRequest) GetSorter() string {
	if x != nil {
		return x.Sorter
	}
	return ""
}

type ListGasDetectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Content []*GasDetectResponse `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *ListGasDetectResponse) Reset() {
	*x = ListGasDetectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGasDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGasDetectResponse) ProtoMessage() {}

func (x *ListGasDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGasDetectResponse.ProtoReflect.Descriptor instead.
func (*ListGasDetectResponse) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{4}
}

func (x *ListGasDetectResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGasDetectResponse) GetContent() []*GasDetectResponse {
	if x != nil {
		return x.Content
	}
	return nil
}

type GasDetectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedTime string    `protobuf:"bytes,1,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Metrics     []*Metric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *GasDetectResponse) Reset() {
	*x = GasDetectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GasDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasDetectResponse) ProtoMessage() {}

func (x *GasDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasDetectResponse.ProtoReflect.Descriptor instead.
func (*GasDetectResponse) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{5}
}

func (x *GasDetectResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GasDetectResponse) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *GasDetectResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetGasDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGasDetectRequest) Reset() {
	*x = GetGasDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGasDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGasDetectRequest) ProtoMessage() {}

func (x *GetGasDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGasDetectRequest.ProtoReflect.Descriptor instead.
func (*GetGasDetectRequest) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{6}
}

func (x *GetGasDetectRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGasDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGasDetectRequest) Reset() {
	*x = DeleteGasDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gas_gas_detect_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGasDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGasDetectRequest) ProtoMessage() {}

func (x *DeleteGasDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gas_gas_detect_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGasDetectRequest.ProtoReflect.Descriptor instead.
func (*DeleteGasDetectRequest) Descriptor() ([]byte, []int) {
	return file_api_gas_gas_detect_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGasDetectRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_gas_gas_detect_proto protoreflect.FileDescriptor

var file_api_gas_gas_detect_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x73, 0x2f, 0x67, 0x61, 0x73, 0x5f, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73,
	0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x22, 0x72, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x4a, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61,
	0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x73,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x62, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x73, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x47,
	0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x11, 0x47, 0x61, 0x73,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x29, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x73, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xc9, 0x03, 0x0a,
	0x10, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x74, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x73, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e,
	0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x61, 0x73, 0x2d, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x65, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e,
	0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x61, 0x73, 0x2d, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2f, 0x67, 0x65, 0x74, 0x12, 0x6a,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x18, 0x2a, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x73, 0x2d, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x6c, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x61, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x67, 0x61, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x73, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x16, 0x12, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x73, 0x2d, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x18, 0x5a, 0x16, 0x67, 0x61, 0x73, 0x2d,
	0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x73, 0x2f, 0x67,
	0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gas_gas_detect_proto_rawDescOnce sync.Once
	file_api_gas_gas_detect_proto_rawDescData = file_api_gas_gas_detect_proto_rawDesc
)

func file_api_gas_gas_detect_proto_rawDescGZIP() []byte {
	file_api_gas_gas_detect_proto_rawDescOnce.Do(func() {
		file_api_gas_gas_detect_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gas_gas_detect_proto_rawDescData)
	})
	return file_api_gas_gas_detect_proto_rawDescData
}

var file_api_gas_gas_detect_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_gas_gas_detect_proto_goTypes = []interface{}{
	(*CreateGasDetectBody)(nil),    // 0: api.gas.CreateGasDetectBody
	(*Metric)(nil),                 // 1: api.gas.Metric
	(*CreateGasDetectRequest)(nil), // 2: api.gas.CreateGasDetectRequest
	(*ListGasDetectRequest)(nil),   // 3: api.gas.ListGasDetectRequest
	(*ListGasDetectResponse)(nil),  // 4: api.gas.ListGasDetectResponse
	(*GasDetectResponse)(nil),      // 5: api.gas.GasDetectResponse
	(*GetGasDetectRequest)(nil),    // 6: api.gas.GetGasDetectRequest
	(*DeleteGasDetectRequest)(nil), // 7: api.gas.DeleteGasDetectRequest
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_api_gas_gas_detect_proto_depIdxs = []int32{
	1, // 0: api.gas.CreateGasDetectBody.metrics:type_name -> api.gas.Metric
	0, // 1: api.gas.CreateGasDetectRequest.body:type_name -> api.gas.CreateGasDetectBody
	5, // 2: api.gas.ListGasDetectResponse.content:type_name -> api.gas.GasDetectResponse
	1, // 3: api.gas.GasDetectResponse.metrics:type_name -> api.gas.Metric
	2, // 4: api.gas.GasDetectService.CreateGasDetect:input_type -> api.gas.CreateGasDetectRequest
	6, // 5: api.gas.GasDetectService.GetGasDetect:input_type -> api.gas.GetGasDetectRequest
	7, // 6: api.gas.GasDetectService.DeleteGasDetect:input_type -> api.gas.DeleteGasDetectRequest
	3, // 7: api.gas.GasDetectService.ListGasDetect:input_type -> api.gas.ListGasDetectRequest
	5, // 8: api.gas.GasDetectService.CreateGasDetect:output_type -> api.gas.GasDetectResponse
	5, // 9: api.gas.GasDetectService.GetGasDetect:output_type -> api.gas.GasDetectResponse
	8, // 10: api.gas.GasDetectService.DeleteGasDetect:output_type -> google.protobuf.Empty
	4, // 11: api.gas.GasDetectService.ListGasDetect:output_type -> api.gas.ListGasDetectResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_gas_gas_detect_proto_init() }
func file_api_gas_gas_detect_proto_init() {
	if File_api_gas_gas_detect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gas_gas_detect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGasDetectBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGasDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGasDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGasDetectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GasDetectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGasDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gas_gas_detect_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGasDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gas_gas_detect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gas_gas_detect_proto_goTypes,
		DependencyIndexes: file_api_gas_gas_detect_proto_depIdxs,
		MessageInfos:      file_api_gas_gas_detect_proto_msgTypes,
	}.Build()
	File_api_gas_gas_detect_proto = out.File
	file_api_gas_gas_detect_proto_rawDesc = nil
	file_api_gas_gas_detect_proto_goTypes = nil
	file_api_gas_gas_detect_proto_depIdxs = nil
}
